### PR TITLE
Update repository to use ODK 1.4

### PR DESCRIPTION
**Pull request by anitacaron**
Working with @zoependlington to update the repository.

- The template `gaz_xrefs.tsv` was transformed into a component `components/gaz_xrefs.owl` and then merged in the `hancestro-edit.ofn`
- The imports were merged into one file `imports/merged_import.owl`

### CODE REVIEW

**Comment by daniwelter** [comment]
@anitacaron I haven't had a chance to dive into the details yet but something is going very badly wrong here. `hancestro_base.owl` looks fine and as expected but `hancestro.owl` and `hancestro_full.owl` are a complete mess. There's a bunch of classes where the annotations don't import correctly, as well as the whole upper section of the BFO-compliant structure, but the HANCESTRO native classes are still at root level. 

I'll try to find some time later this week to go over this with a fine toothcomb and figure out where it falls over. Any pointers welcome.

**Comment by daniwelter** [comment]
@anitacaron as I said, something somewhere has gone very badly wrong. I'm currently working my way through the Makefile to see where things might have fallen over.

Here for comparison the current `hancestro_inferred.owl` and the new `hancestro_full.owl`
Screenshot 2023-07-13 at 15 39 25

**Comment by daniwelter** [comment]
Ok, I think I can see the problems. For one, the OBI import was incorporated into the non-BFO version whereas it should only be in the BFO version. Also, there's some stripping of the GEO import that needs to happen and I don't think it does. I'll try to reverse-engineer the individual steps tomorrow so I know what the artefacts look like vs what they should look like, and then we can see how we can fix this monster.

**Comment by anitacaron** [comment]
No need to worry, @daniwelter. The dangling classes come from the new way I created the imports. If this is an issue, I can create each import, which will look more like the previous version.

**Pull request merged**
